In [1]:
!pip install jovian --upgrade -q
import jovian
jovian.utils.colab.set_colab_file_id('lVRbUpx8uF22Tzy2_xRmLw09h-ytekiAm')

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 68.6/68.6 kB 630.0 kB/s eta 0:00:00
  Preparing metadata (setup.py) ... done


let's import the **torch** module

In [2]:
import torch

**Tensors**

PyTorch est une bibliothèque permettant de traiter les tensors. Un tensor est un nombre, un vecteur, une matrice ou tout autre tableau à n dimensions.

In [3]:
# Number
t1= torch.tensor(4.)
t1

tensor(4.)

4. est un raccourci pour 4.0 .Il est utilisé pour indiquer à Python (et PyTorch) que vous voulez créer un nombre à virgule flottante . Nous pouvons le vérifier en contrôlant l'attribut **dtype** de notre tenseur

In [4]:
t1.dtype

torch.float32

In [5]:
# vector
t2=torch.tensor([1. , 2 , 3 , 4])
t2

tensor([1., 2., 3., 4.])

In [10]:
t2.dtype

torch.float32

In [7]:
#Matrix
t3 = torch.tensor([[5., 6],
                   [7 , 8],
                   [9 , 10]])
t3

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [11]:
t3.dtype

torch.float32

In [9]:
#3-dimensional array
t4 = torch.tensor([
    [[11,12,13],
     [13,14,15]],
    [[15,16,17],
     [17,18,19.]]
    ])
t4

tensor([[[11., 12., 13.],
         [13., 14., 15.]],

        [[15., 16., 17.],
         [17., 18., 19.]]])

In [12]:
t4.dtype

torch.float32

Les Tensors peuvent avoir un nombre quelconque de dimensions et différentes longueurs le long de chaque dimension. Nous pouvons vérifier la longueur le long de chaque dimension en utilisant la propriété **.shape** d'un tensor.

In [14]:
print(t1)
t1.shape

tensor(4.)


torch.Size([])

In [15]:
print(t2)
t2.shape

tensor([1., 2., 3., 4.])


torch.Size([4])

In [16]:
print(t3)
t3.shape

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])


torch.Size([3, 2])

In [17]:
print(t4)
t4.shape

tensor([[[11., 12., 13.],
         [13., 14., 15.]],

        [[15., 16., 17.],
         [17., 18., 19.]]])


torch.Size([2, 2, 3])

**Tensor operations and gradients**

nous pouvons combiner les tensors avec les opérations arithmétiques habituelles

In [26]:
#Create tensors
x = torch.tensor(3.)
w = torch.tensor(4. , requires_grad=True)
b = torch.tensor(6. , requires_grad=True)
x , w , b

(tensor(3.), tensor(4., requires_grad=True), tensor(6., requires_grad=True))

Nous avons créé trois tenseurs : x , w et b , tous des nombres. w et b ont un paramètre supplémentaire "requires_grad" fixé à "True" .

In [27]:
# Arithmetic operations
y = w * x + b
y

tensor(18., grad_fn=<AddBackward0>)

Comme prévu, y est un tensor avec la valeur 3 * 4 + 6 = 18. La particularité de PyTorch est que nous pouvons calculer automatiquement la dérivée de y par rapport aux tensors pour lesquels la
valeur de requires_grad est True, c'est-à-dire w et b.
Pour calculer les dérivées, nous pouvons appeler la méthode .backward sur notre résultat y.

In [28]:
# Compute derivatives
y.backward()

Les dérivées de y par rapport aux tenseurs d'entrée sont stockées dans la propriété .grad des tenseurs respectifs.

In [29]:
# Display gradients
print('dy/dx:', x.grad)
print('dy/dw:', w.grad)
print('dy/db:', b.grad)

dy/dx: None
dy/dw: tensor(3.)
dy/db: tensor(1.)


Comme prévu, `dy/dw` a la même valeur que `x`, c'est-à-dire `3`, et `dy/db` a la valeur `1`. Notez que `x.grad` est `None`, parce que `x` n'a pas la valeur `True` dans `requires_grad`.

Le "grad" dans `w.grad` signifie gradient, qui est un autre terme pour la dérivée, utilisé principalement pour les matrices.

**Tensor functions**

En plus des opérations aérométriques, le module `torch` contient également de nombreuses fonctions pour créer et manipuler des tensors.

In [34]:
#Create a tensor with a fixed value for every element
t6 = torch.full((3 , 2) , 42)
t6

tensor([[42, 42],
        [42, 42],
        [42, 42]])

In [39]:
t3

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [36]:
#Concatenate two tensors with compatible shapes
t7 = torch.cat((t3 , t6))
t7

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.],
        [42., 42.],
        [42., 42.],
        [42., 42.]])

In [37]:
# Compute the sin of each element
t8 = torch.sin(t7)
t8

tensor([[-0.9589, -0.2794],
        [ 0.6570,  0.9894],
        [ 0.4121, -0.5440],
        [-0.9165, -0.9165],
        [-0.9165, -0.9165],
        [-0.9165, -0.9165]])

In [40]:
# Change the shape of a tensor
t9 = t8.reshape(3, 2, 2)
t9

tensor([[[-0.9589, -0.2794],
         [ 0.6570,  0.9894]],

        [[ 0.4121, -0.5440],
         [-0.9165, -0.9165]],

        [[-0.9165, -0.9165],
         [-0.9165, -0.9165]]])

**Interoperability with Numpy**

Au lieu de réinventer la roue, PyTorch interagit très bien avec Numpy pour tirer parti de son écosystème existant d'outils et de bibliothèques.

Voici comment créer un tableau dans Numpy :

In [30]:
import numpy as np

x = np.array([[1, 2], [3, 4.]])
x

array([[1., 2.],
       [3., 4.]])

Nous pouvons convertir un tableau Numpy en un tensor PyTorch en utilisant `torch.from_numpy`.




In [31]:
# Convert the numpy array to a torch tensor.
y = torch.from_numpy(x)
y

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

Vérifions que les tableaux numpy et les tensolrs torch ont des types de données similaires.

In [32]:
x.dtype, y.dtype

(dtype('float64'), torch.float64)

Nous pouvons convertir un tensor PyTorch en un tableau Numpy en utilisant la méthode `.numpy` d'un tensor.

In [33]:
# Convert a torch tensor to a numpy array
z = y.numpy()
z

array([[1., 2.],
       [3., 4.]])

L'interopérabilité entre PyTorch et Numpy est vraiment importante car la plupart des ensembles de données avec lesquels vous travaillerez seront probablement lus et prétraités sous forme de tableaux Numpy.
Vous pouvez vous demander pourquoi nous avons besoin d'une bibliothèque comme PyTorch puisque Numpy fournit déjà des structures de données et des utilitaires pour travailler avec des données numériques multidimensionnelles . Il y a deux raisons principales :
1. **Autograd** : La capacité à calculer
automatiquement les gradients pour les opérations tensorielles est essentielle pour la formation des modèles d'apprentissage profond.
2. **GPU support** : lors du travail avec des ensembles de données massifs et des modèles de grande taille. Les opérations tensorielles de PyTorch peuvent être effectuées efficacement à l'aide d'une unité de traitement graphique (GPU). Les calculs qui peuvent prendre des heures peuvent être effectués en quelques minutes grâce aux GPU.


**Save and upload your notebook**

In [1]:
!pip install jovian --upgrade --quiet

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 68.6/68.6 kB 851.0 kB/s eta 0:00:00
  Preparing metadata (setup.py) ... done


In [2]:
import jovian

In [3]:
jovian.commit(project='0l-pytorch-basics-live')

[jovian] Detected Colab notebook...
[jovian] jovian.commit() is no longer required on Google Colab. If you ran this notebook from Jovian, 
then just save this file in Colab using Ctrl+S/Cmd+S and it will be updated on Jovian. 
Also, you can also delete this cell, it's no longer necessary.
